// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Z-c2jHvRIVzTdRhczP7aJYWDNHDhyXQ',
    appId: '1:864444807304:web:d6fdd0cd75c2d2ac22473d',
    messagingSenderId: '864444807304',
    projectId: 'chatbot-app-91842',
    authDomain: 'chatbot-app-91842.firebaseapp.com',
    storageBucket: 'chatbot-app-91842.appspot.com',
    measurementId: 'G-D0RPXGWX2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb6eFp9ocGCE9UtDoMrBN5j_2h09vDI94',
    appId: '1:864444807304:android:ce1c0ec4f23ad55922473d',
    messagingSenderId: '864444807304',
    projectId: 'chatbot-app-91842',
    storageBucket: 'chatbot-app-91842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE4LwxNI30NFpv3H1LXUMSayhs1fXXkfI',
    appId: '1:864444807304:ios:4d3f154b419c5eb222473d',
    messagingSenderId: '864444807304',
    projectId: 'chatbot-app-91842',
    storageBucket: 'chatbot-app-91842.appspot.com',
    iosClientId: '864444807304-qc0snllfpkc6jmhhm56jgckb7s4l6fkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE4LwxNI30NFpv3H1LXUMSayhs1fXXkfI',
    appId: '1:864444807304:ios:4d3f154b419c5eb222473d',
    messagingSenderId: '864444807304',
    projectId: 'chatbot-app-91842',
    storageBucket: 'chatbot-app-91842.appspot.com',
    iosClientId: '864444807304-qc0snllfpkc6jmhhm56jgckb7s4l6fkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbotApp',
  );
}
